const translations = {
    ko: {
        "reservation-btn": "비회원 예약",
        "about-link": "호텔 소개",
        "rooms-link": "객실",
        "facilities-link": "편의 시설",
        "contact-link": "연락처",
        "attractions-link": "주변 관광",
        "developer-link": "사이트 개발자",
        "hotel-name": "임페리얼 사이공 한인호텔",
        "hotel-description": "호치민시 한인 타운(푸미흥)에 위치한 한인이 직접 운영하는 임페리얼 사이공 호텔입니다.",
        "hotel-area": "푸미흥은 한국인들이 많이 거주하는 지역으로, 안전하고 쾌적한 환경을 제공합니다.",
        "banquet-title": "연회장 소개",
        "banquet-description": "호텔 1층에는 최대 60명 이상 수용할 수 있는 연회장이 있습니다.",
        "meeting-room-title": "미팅 룸 소개",
        "meeting-room-description": "10명 이상의 인원을 수용할 수 있는 독립된 미팅 룸이 있습니다.",
        "terrace-title": "야외 테라스 소개",
        "terrace-description": "20명 이상이 이용할 수 있는 테라스가 마련되어 있습니다.",
        "room-title": "객실 소개",
        "suite-room": "스위트 룸: 42m² (3실)",
        "imperial-room": "임페리얼 룸: 28m² (43실)",
        "standard-room": "스탠다드 룸: 21m² (8실)",
        "room-description": "총 54개의 객실을 보유하고 있으며, 각 객실은 넓고 편안한 휴식을 제공합니다.",
        "footer": "호텔 이름",
        "reservation-title": "비회원 예약",
        "name-label": "이름:",
        "email-label": "이메일:",
        "checkin-label": "체크인 날짜:",
        "checkout-label": "체크아웃 날짜:",
        "guests-label": "인원:",
        "submit-btn": "예약하기",
        "secret-code-label": "예약 확인을 위한 비밀 번호:",
        "check-reservation-title": "예약 확인",
        "email-check-label": "이메일:",
        "code-check-label": "비밀 번호:",
        "check-reservation-btn": "예약 확인하기",
        "attractions-title": "주변 관광지",
        "hotel-name": "임페리얼 사이공 한인호텔",
        "hotel-description": "호치민시 한인 타운(푸미흥)에 위치한 한인이 직접 운영하는 임페리얼 사이공 호텔입니다.",
        "hotel-area": "푸미흥은 한국인들이 많이 거주하는 지역으로, 안전하고 쾌적한 환경을 제공합니다.",
        "banquet-title": "연회장 소개",
        "banquet-description": "호텔 1층에는 최대 60명 이상 수용할 수 있는 연회장이 있습니다.",
        "meeting-room-title": "미팅 룸 소개",
        "meeting-room-description": "10명 이상의 인원을 수용할 수 있는 독립된 미팅 룸이 있습니다.",
        "terrace-title": "야외 테라스 소개",
        "terrace-description": "20명 이상이 이용할 수 있는 테라스가 마련되어 있습니다.",
        "vung-tau-title": "붕따우 (Vũng Tàu)",
        "vung-tau-description": "호치민시에서 약 2시간 거리에 위치한 붕따우는 해변과 문화 명소로 유명한 휴양지입니다.",
        "can-gio-title": "깐저 (Cần Giờ) 생물권 보전 지역",
        "can-gio-description": "깐저는 유네스코가 지정한 맹그로브 숲과 야생동물 보호 지역입니다.",
        "binh-quoi-title": "빈꾸이 관광지구 (Bình Quới Tourist Village)",
        "binh-quoi-description": "호치민시 근처의 전통적인 베트남 마을을 재현한 관광지입니다.",
        "ho-tram-title": "호짬 해변 (Hồ Tràm Beach)",
        "ho-tram-description": "평화로운 해변으로, 휴식과 치유를 위한 장소로 유명합니다.",
        "my-tho-title": "미토 (Mỹ Tho)",
        "my-tho-description": "메콩 델타 지역의 중심지로, 메콩강 보트 투어를 즐길 수 있는 곳입니다.",
        "contact-title": "연락처",
        "contact-description": "호텔에 대한 문의 사항이 있으시면 언제든지 연락 주십시오.",
        "phone-label": "전화번호: +84 123 456 789",
        "email-label": "이메일: contact@imperialhotel.com",
        "address-label": "주소: 123 Phu My Hung, District 7, Ho Chi Minh City, Vietnam",
        "name-label": "이름:",
        "email-form-label": "이메일:",
        "message-label": "메시지:",
        "submit-contact-btn": "문의하기",
        "developer-title": "사이트 개발자",
        "developer-name": "이름: 황선준 (Sunjoon Hwang)",
        "developer-role": "역할: 풀스택 웹 개발자 (Full Stack Web Developer)",
        "developer-description": "저는 웹 개발, AI 관련 기술, 그리고 양자컴퓨팅 기술에 관심이 많은 개발자입니다. 현재 호텔 웹사이트 개발 및 유지보수 작업을 담당하고 있으며, 인공지능과 양자컴퓨팅을 활용한 프로젝트도 진행하고 있습니다.",
        "contact-message": "웹프로그래밍과 AI 또는 양자컴퓨팅 기술에 관심이 있으신 분들은 언제든지 편하게 연락주세요."

    },
    en: {
        "reservation-btn": "Guest Reservation",
        "about-link": "About",
        "rooms-link": "Rooms",
        "facilities-link": "Facilities",
        "contact-link": "Contact",
        "attractions-link": "Attractions",
        "developer-link": "Site Developer",
        "hotel-name": "Imperial Saigon Hotel",
        "hotel-description": "Imperial Saigon Hotel is located in Phu My Hung, a Korean town in Ho Chi Minh City, and is directly operated by Koreans.",
        "hotel-area": "Phu My Hung is a safe and comfortable area where many Koreans reside. It offers various Korean restaurants, facilities, and easy access to SECC (Saigon Exhibition Convention Center).",
        "banquet-title": "Banquet Hall",
        "banquet-description": "The hotel has a banquet hall on the first floor that can accommodate over 60 guests, offering breakfast and various meals.",
        "meeting-room-title": "Meeting Room",
        "meeting-room-description": "There is an independent meeting room for more than 10 people equipped with PC, fax, and copy machine.",
        "terrace-title": "Outdoor Terrace",
        "terrace-description": "The outdoor terrace accommodates more than 20 people, providing a quiet space for guests to relax and enjoy coffee or tea.",
        "room-title": "Room Information",
        "suite-room": "Suite Room: 42m² (3 rooms)",
        "imperial-room": "Imperial Room: 28m² (43 rooms)",
        "standard-room": "Standard Room: 21m² (8 rooms)",
        "room-description": "The hotel offers 54 spacious and comfortable rooms equipped with Wi-Fi, air conditioning, minibar, refrigerator, cable TV, and a safe.",
        "footer": "Hotel Name",
        "reservation-title": "Guest Reservation",
        "name-label": "Name:",
        "email-label": "Email:",
        "checkin-label": "Check-in Date:",
        "checkout-label": "Check-out Date:",
        "guests-label": "Guests:",
        "submit-btn": "Book Now",
        "secret-code-label": "Secret Code for Reservation Check:",
        "check-reservation-title": "Check Reservation",
        "email-check-label": "Email:",
        "code-check-label": "Secret Code:",
        "check-reservation-btn": "Check Reservation",
        "attractions-title": "Nearby Attractions",
        "hotel-name": "Imperial Saigon Hotel",
        "hotel-description": "Imperial Saigon Hotel is located in Phu My Hung, a Korean town in Ho Chi Minh City.",
        "hotel-area": "Phu My Hung is a safe and pleasant area where many Koreans reside.",
        "banquet-title": "Banquet Hall",
        "banquet-description": "The hotel has a banquet hall on the first floor that can accommodate over 60 people.",
        "meeting-room-title": "Meeting Room",
        "meeting-room-description": "There is an independent meeting room for more than 10 people.",
        "terrace-title": "Outdoor Terrace",
        "terrace-description": "A terrace that accommodates more than 20 people is provided.",
        "vung-tau-title": "Vũng Tàu",
        "vung-tau-description": "Located about 2 hours from Ho Chi Minh City, Vũng Tàu is known for its beaches and cultural landmarks.",
        "can-gio-title": "Cần Giờ Biosphere Reserve",
        "can-gio-description": "Cần Giờ is a UNESCO-recognized mangrove forest and wildlife conservation area.",
        "binh-quoi-title": "Bình Quới Tourist Village",
        "binh-quoi-description": "A re-creation of a traditional Vietnamese village near Ho Chi Minh City.",
        "ho-tram-title": "Hồ Tràm Beach",
        "ho-tram-description": "A peaceful beach famous for relaxation and healing experiences.",
        "my-tho-title": "Mỹ Tho",
        "my-tho-description": "A city in the Mekong Delta, offering boat tours and fresh fruit markets.",
        "contact-title": "Contact Us",
        "contact-description": "Please feel free to contact us with any inquiries about the hotel.",
        "phone-label": "Phone: +84 123 456 789",
        "email-label": "Email: contact@imperialhotel.com",
        "address-label": "Address: 123 Phu My Hung, District 7, Ho Chi Minh City, Vietnam",
        "name-label": "Name:",
        "email-form-label": "Email:",
        "message-label": "Message:",
        "submit-contact-btn": "Submit Inquiry",
        "developer-title": "Site Developer",
        "developer-name": "Name: Sunjoon Hwang",
        "developer-role": "Role: Full Stack Web Developer",
        "developer-description": "I am a developer interested in web development, AI-related technologies, and quantum computing. I am currently responsible for developing and maintaining this hotel website, and I am also involved in AI and quantum computing projects.",
        "contact-message": "If you're interested in web programming, AI, or quantum computing, feel free to contact me anytime."

    },
    vi: {
        "reservation-btn": "Đặt phòng khách",
        "about-link": "Giới thiệu",
        "rooms-link": "Phòng",
        "facilities-link": "Tiện nghi",
        "contact-link": "Liên hệ",
        "attractions-link": "Điểm tham quan",
        "developer-link": "Nhà phát triển trang web",
        "hotel-name": "Khách sạn Imperial Sài Gòn",
        "hotel-description": "Khách sạn Imperial Sài Gòn tọa lạc tại Phú Mỹ Hưng, một khu phố Hàn Quốc tại Thành phố Hồ Chí Minh và được vận hành trực tiếp bởi người Hàn Quốc.",
        "hotel-area": "Phú Mỹ Hưng là khu vực an toàn và thoải mái, nơi có nhiều người Hàn Quốc sinh sống. Khách sạn cung cấp nhiều nhà hàng Hàn Quốc, tiện nghi và dễ dàng tiếp cận SECC (Trung tâm Triển lãm Sài Gòn).",
        "banquet-title": "Phòng Tiệc",
        "banquet-description": "Khách sạn có phòng tiệc tại tầng một có thể chứa hơn 60 khách, cung cấp bữa sáng và các bữa ăn đa dạng.",
        "meeting-room-title": "Phòng Họp",
        "meeting-room-description": "Có phòng họp độc lập cho hơn 10 người, được trang bị PC, máy fax và máy photocopy.",
        "terrace-title": "Sân Thượng Ngoài Trời",
        "terrace-description": "Sân thượng ngoài trời có sức chứa hơn 20 người, cung cấp không gian yên tĩnh để thư giãn và thưởng thức cà phê hoặc trà.",
        "room-title": "Giới thiệu Phòng",
        "suite-room": "Phòng Suite: 42m² (3 phòng)",
        "imperial-room": "Phòng Imperial: 28m² (43 phòng)",
        "standard-room": "Phòng Standard: 21m² (8 phòng)",
        "room-description": "Khách sạn có 54 phòng rộng rãi và thoải mái, được trang bị Wi-Fi, điều hòa, minibar, tủ lạnh, TV cáp và két an toàn.",
        "footer": "Tên khách sạn",
        "reservation-title": "Đặt phòng khách",
        "name-label": "Tên:",
        "email-label": "Email:",
        "checkin-label": "Ngày nhận phòng:",
        "checkout-label": "Ngày trả phòng:",
        "guests-label": "Số khách:",
        "submit-btn": "Đặt phòng ngay",
        "secret-code-label": "Mã bí mật để kiểm tra đặt phòng:",
        "check-reservation-title": "Kiểm tra đặt phòng",
        "email-check-label": "Email:",
        "code-check-label": "Mã bí mật:",
        "check-reservation-btn": "Kiểm tra đặt phòng",
        "attractions-title": "Địa điểm du lịch",
        "hotel-name": "Khách sạn Imperial Sài Gòn",
        "hotel-description": "Khách sạn Imperial Sài Gòn nằm ở Phú Mỹ Hưng, một khu phố Hàn Quốc tại Thành phố Hồ Chí Minh.",
        "hotel-area": "Phú Mỹ Hưng là khu vực an toàn và thoải mái, nơi nhiều người Hàn Quốc sinh sống.",
        "banquet-title": "Phòng tiệc",
        "banquet-description": "Khách sạn có một phòng tiệc ở tầng một có thể chứa hơn 60 người.",
        "meeting-room-title": "Phòng họp",
        "meeting-room-description": "Có một phòng họp độc lập dành cho hơn 10 người.",
        "terrace-title": "Sân thượng ngoài trời",
        "terrace-description": "Sân thượng có thể chứa hơn 20 người được cung cấp.",
        "vung-tau-title": "Vũng Tàu",
        "vung-tau-description": "Nằm cách Thành phố Hồ Chí Minh khoảng 2 giờ, Vũng Tàu nổi tiếng với các bãi biển và danh lam thắng cảnh.",
        "can-gio-title": "Khu dự trữ sinh quyển Cần Giờ",
        "can-gio-description": "Cần Giờ là khu rừng ngập mặn và bảo tồn động vật hoang dã được UNESCO công nhận.",
        "binh-quoi-title": "Khu du lịch Bình Quới",
        "binh-quoi-description": "Tái hiện một ngôi làng truyền thống của Việt Nam gần Thành phố Hồ Chí Minh.",
        "ho-tram-title": "Bãi biển Hồ Tràm",
        "ho-tram-description": "Một bãi biển yên tĩnh nổi tiếng với trải nghiệm thư giãn và chữa bệnh.",
        "my-tho-title": "Mỹ Tho",
        "my-tho-description": "Một thành phố ở Đồng bằng sông Cửu Long, cung cấp các tour du thuyền và chợ trái cây tươi.",
        "contact-title": "Liên hệ",
        "contact-description": "Vui lòng liên hệ với chúng tôi nếu bạn có bất kỳ câu hỏi nào về khách sạn.",
        "phone-label": "Số điện thoại: +84 123 456 789",
        "email-label": "Email: contact@imperialhotel.com",
        "address-label": "Địa chỉ: 123 Phu My Hung, Quận 7, Thành phố Hồ Chí Minh, Việt Nam",
        "name-label": "Tên:",
        "email-form-label": "Email:",
        "message-label": "Tin nhắn:",
        "submit-contact-btn": "Gửi tin nhắn",
        "developer-title": "Nhà phát triển trang web",
        "developer-name": "Tên: Sunjoon Hwang",
        "developer-role": "Vai trò: Nhà phát triển web toàn diện (Full Stack Web Developer)",
        "developer-description": "Tôi là một nhà phát triển quan tâm đến phát triển web, công nghệ AI và điện toán lượng tử. Hiện tại tôi chịu trách nhiệm phát triển và duy trì trang web khách sạn này và tham gia các dự án liên quan đến AI và điện toán lượng tử.",
        "contact-message": "Nếu bạn quan tâm đến lập trình web, AI hoặc điện toán lượng tử, đừng ngần ngại liên hệ với tôi bất cứ lúc nào."
    }
};


// 언어 변경 함수
function changeLanguage(language) {
    const elementsToTranslate = document.querySelectorAll("[data-translate]");
    
    elementsToTranslate.forEach(element => {
        const key = element.getAttribute("data-translate");
        element.textContent = translations[language][key];
    });
    
    localStorage.setItem("language", language);  // 선택한 언어를 localStorage에 저장
}

// 페이지 로드 시 저장된 언어 적용
window.addEventListener("DOMContentLoaded", () => {
    const savedLanguage = localStorage.getItem("language") || "ko";  // 기본값은 한국어
    changeLanguage(savedLanguage);
    document.getElementById("language-select").value = savedLanguage;  // 드롭다운 선택된 언어 설정
});
